NeomSoft/Controllers/FinAccountController.cs
using NeomSoft.Logic.Models;
using NeomSoft.Logic.ViewModels;
using NeomSoft.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace NeomSoft.Controllers
{
    public class FinAccountController : Controller
    {
        // GET: FinAccount
        public async Task<ActionResult> Index(string searchText)
        {
            var list = await FinAccountModel.GetAccountsList(searchText);
            return View(list);
        }

        public async Task<ActionResult> AccountData(int id)
        {
            var model = await FinAccountModel.GetAccount(id);

            ViewData["AcctsList"] = await FinAccountModel.GetAccountsList();
            ViewData["CurrenciesList"] = await FinAccountModel.GetCurrenciesList();
            return View(model);
        }

        public async Task<ActionResult> CreateAccount()
        {
            ViewData["AcctsList"] = await FinAccountModel.GetAccountsList();
            ViewData["CurrenciesList"] = await FinAccountModel.GetCurrenciesList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAccount(FinAccountViewModel model)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    var resp = await FinAccountModel.CreateAccount(model, User.Identity.Name);

                    if (resp.IsSuccess)
                    {
                        ViewData["SuccessAdd"] = $"تم إضافة الحساب {model.Code} - {model.NameAr} بنجاح";
                        model = null;
                    }
                    else
                    {
                        ModelState.AddModelError("", resp.Message);
                    }
                }

            }
            catch (Exception ex)
            {

            }

            ViewData["CurrenciesList"] = await FinAccountModel.GetCurrenciesList();
            ViewData["AcctsList"] = await FinAccountModel.GetAccountsList();
            return View(model);
        }

        [Authorize]
        public async Task<ActionResult> EditAccount(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = await FinAccountModel.GetAccount(id.Value);
            if (model == null)
            {
                return HttpNotFound();
            }

            model.SelectedCurrencies = model.Currencies.Select(e => e.CurrencyID).ToList();

            ViewData["AcctsList"] = await FinAccountModel.GetAccountsList();
            ViewData["CurrenciesList"] = await FinAccountModel.GetCurrenciesList();
            return View(model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAccount(FinAccountViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var resp = await FinAccountModel.EditAccount(model, User.Identity.Name);

                    if (resp.IsSuccess)
                    {
                        ViewData["SuccessAdd"] = $"تم تعديل بيانات الحساب {model.Code} - {model.NameAr} بنجاح";
                    }
                    else
                    {
                        ModelState.AddModelError("", resp.Message);
                    }
                }

            }
            catch (Exception ex)
            {

            }

            ViewData["CurrenciesList"] = await FinAccountModel.GetCurrenciesList();
            ViewData["AcctsList"] = await FinAccountModel.GetAccountsList();
            return View(model);
        }

        [Authorize]
        public async Task<ActionResult> DeleteAccount(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            var finAccountViewModel = await FinAccountModel.GetAccount(id.Value);

            if (finAccountViewModel == null)
            {
                return HttpNotFound();
            }

            return View(finAccountViewModel);
        }

        [Authorize]
        [HttpPost, ActionName("DeleteAccount")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var result = await FinAccountModel.DeleteAccount(id, User.Identity.Name);
            if (result.IsSuccess)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["ErrorMsg"] = result.Message;
                var finAccountViewModel = await FinAccountModel.GetAccount(id);
                return View(finAccountViewModel);
            }
        }


    }
}

NeomSoft/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NeomSoft.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NeomSoft/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NeomSoft/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NeomSoft/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>نيوم سوفت - Neom Soft</h1>
</div>


<div>
    <ul>
        <li>@Html.ActionLink("بإمكانك الإنتقال إلى صفحة بيانات الحسابات من هنا", "Index", "FinAccount")</li>
        <li>يتطلب تسجيل الدخول للقيام بعمليات الحذف والإضافة والتعديل على الحسابات</li>
        <li>@Html.ActionLink("بإمكانك الإنتقال إلى صفحة تسجيل الدخول", "Login", "Account") بعد القيام بعملية  @Html.ActionLink("التسجيل من هنا", "Register", "Account")</li>
        <li>تم تقسيم المشروع إلى43 مشاريع حسب الوظائف
        <ol>
            <li><strong> NeomSoft:</strong> مشروع الويب الرئيسي باستخدام ASP.NET MVC</li>
            <li><strong>NeomSoft.DB:</strong> للقيام بوظيفة ال Data layer </li>
            <li><strong>NeomSoft.Logic:</strong> للقيام بوظيفة ال Business layer</li>
            <li><strong>NeomSoft.API:</strong> للقيام بوظيفة ال API وتمكين استخدامها من قبل الأطراف الثانوية</li>
        </ol>
        </li>
        <li>يمكن عمل طباعة التقارير باستخدام Report Viewer لتبدو أكثر احترافية ولكن حاليا تم استخدام طريقة بسيطة وسريقة لتأدية الغرض</li>
        <li>تم استخدام صفحة تسجيل الدخول الإفتراضية التي تتبع قالب المشروع الذي توفرة Microsoft وبالإمكان عمل تعديل على جدول بيانات المستخدمين واستخدام نفس التقنية</li>
        <li>لم يتم استخدام Authentication في مشروع ال API حاليا ولكن أنصح باستخدام ASP.NET Identity 2.1 لحماية البيانات من الوصول الغير مصرح</li>

    </ul>
</div>